language: node_js
node_js:
  - "node"

sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - echo "Empty for now"

after_success:
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export RESOURCES=sanedev/resources
  - export TAG=latest
  - sudo docker build -t $RESOURCES:$COMMIT ./resources
  - sudo docker tag $RESOURCES:$COMMIT $RESOURCES:$TAG
  - sudo docker push $RESOURCES