language: node_js
node_js:
  - "node"

sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - echo "Empty for now"

after_success:
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export RESOURCES=sanedev/resources
  - export API=sanedev/api
  - export DATABASE=sanedev/database
  - export TAG=latest
  - sudo docker build -t $RESOURCES:$COMMIT ./resources
  - sudo docker tag $RESOURCES:$COMMIT $RESOURCES:$TAG
  - sudo docker push $RESOURCES
  - sudo docker build -t $API:$COMMIT ./api
  - sudo docker tag $API:$COMMIT $API:$TAG
  - sudo docker push $API
  - sudo docker build -t $DATABASE:$COMMIT ./database
  - sudo docker tag $DATABASE:$COMMIT $DATABASE:$TAG
  - sudo docker push $DATABASE