version: '3'
services: 
  resources:
    container_name: resources
    build: ./resources
    environment:
      - DEFAULT_HOST=sanedev.dev
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${IMAGES_DIR}:/var/www/public/images/
    ports:
      - "80:80"
      - "443:443"
  web:
    container_name: web
    build: ./web
    environment:
      - VIRTUAL_HOST=sanedev.dev
      - NODE_PATH=./src
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./web/src:/usr/app/src
    ports:
      - "4040:4040"
    env_file:
      - .env
    depends_on:
      - api
  api:
    container_name: api
    build: ./api
    environment:
      - NODE_PATH=./src
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./api/src:/usr/app/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
  database:
    container_name: database
    build: ./database
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
volumes:
  data:
    external: true