version: '3'
services: 
  api:
    container_name: api
    image: sanedev/api
    environment:
      - NODE_ENV=prod
      - NODE_PATH=./src
  resources:
    container_name: resources
    image: sanedev/resources
    restart: always
    ports:
      - "80:80"
      - "443:443"